name: diskplay_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  diacritic: ^0.1.6
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  http: ^1.3.0
  logging: ^1.3.0
  path: ^1.8.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
